# Generated by Django 4.2 on 2023-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('type', models.CharField(choices=[('Alfa', 'Alfa'), ('Touch', 'Touch')], max_length=10, verbose_name='Service Type')),
                ('category', models.CharField(choices=[('Recharge Card', 'Recharge Card'), ('Recharge Day', 'Recharge Day'), ('Alfa Gift', 'Alfa Gift'), ('Weekly Data', 'Weekly Data'), ('Alfa Ushare', 'Alfa Ushare')], max_length=20, verbose_name='Category')),
                ('image', models.CharField(max_length=50, verbose_name='Image Path')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
